Repository silentrald/STSWENG_Reddit, pull requests merged in 2021-02, with the labels that each got.

#59 Feature edit post
  client/components/post.vue
  client/middleware/author.js
  client/pages/s/_station/post/_post/edit.vue
  server/api/postAPI.js
  server/routers/postRtr.js
  server/test/integration/postAPI.spec.js
  server/test/unit/postAPI.test.js
Labels: documentation, enhancement, ui

#56 Feature view user profile
  client/components/post.vue
  client/pages/u/_user.vue
  server/api/postAPI.js
  server/api/userAPI.js
  server/middlewares/userMw.js
  server/migrations/sqls/insert.sql
  server/routers/postRtr.js
  server/routers/userRtr.js
  server/test/integration/postAPI.spec.js
  server/test/integration/userAPI.spec.js
  server/test/unit/postAPI.test.js
  server/test/unit/userAPI.test.js
  server/test/unit/userMw.test.js
Labels: enhancement, ui

#79 Added click on submit button
  client/components/navbar.vue
Labels: fix

#57 Feature moderator roles
  client/components/mod-header.vue
  client/pages/s/_station/mod/roles.vue
  server/api/stationAPI.js
  server/middlewares/stationMw.js
  server/routers/stationRtr.js
  server/test/integration/stationAPI.spec.js
Labels: enhancement, ui

#77 Fix us10A
  client/pages/s/_station/post/_post/index.vue
Labels: fix

#80 Fix us 11 a
  client/components/comment.vue
Labels: fix

#78 Fix us11c
  client/components/comment.vue
Labels: fix

#81 Hidden reply button in subcomments when not joined
  client/components/comment.vue
Labels: fix, ui

#89 Added break text
  client/pages/s/_station/index.vue
  client/pages/s/_station/mod/info.vue
Labels: fix

#88 Added send verification feedback
  client/layouts/default.vue
  client/pages/u/_user.vue
Labels: fix
