Repository silentrald/STSWENG_Reddit, pull requests merged in 2021-01, with the labels that each got.

#18 Feature moderator station info
  client/components/mod-header.vue
  client/package.json
  client/pages/create-station.vue
  client/pages/s/_station/index.vue
  client/pages/s/_station/mod/index.vue
  client/pages/s/_station/mod/info.vue
  client/yarn.lock
  server/api/stationAPI.js
  server/middlewares/stationMw.js
  server/routers/stationRtr.js
  server/test/integration/stationAPI.spec.js
  server/test/unit/stationAPI.test.js
Labels: enhancement, ui

#42 Feature search
  client/components/navbar.vue
  client/layouts/default.vue
  client/pages/s/_station/index.vue
  client/pages/s/_station/mod/info.vue
  client/pages/search.vue
  server/api/postAPI.js
  server/api/stationAPI.js
  server/api/userAPI.js
  server/middlewares/postMw.js
  server/middlewares/queryStringMw.js
  server/routers/postRtr.js
  server/routers/stationRtr.js
  server/routers/userRtr.js
  server/test/integration/postAPI.spec.js
  server/test/integration/stationAPI.spec.js
  server/test/integration/userAPI.spec.js
  server/test/unit/postMw.test.js
  server/test/unit/queryStringMw.test.js
  server/test/unit/stationAPI.test.js
  server/test/unit/userAPI.test.js
Labels: documentation, enhancement, ui

#43 Feature emailer
  server/migrations/sqls/down.sql
Labels: documentation, enhancement, ui

#47 Feature delete comment
  client/components/comment-vote.vue
  client/components/comment.vue
  client/pages/s/_station/post/_post/index.vue
  server/api/commentAPI.js
  server/api/stationAPI.js
  server/middlewares/queryMw.js
  server/middlewares/stationMw.js
  server/migrations/sqls/down.sql
  server/migrations/sqls/insert.sql
  server/routers/commentRtr.js
  server/routers/commentVoteRtr.js
  server/routers/stationRtr.js
  server/test/integration/commentAPI.spec.js
  server/test/integration/commentVoteAPI.spec.js
Labels: enhancement, ui

#55 Fix #19 and #27 403 comment post
  client/pages/s/_station/post/_post/index.vue
  server/api/commentAPI.js
Labels: fix

#48 Feature delete post
  client/components/post-vote.vue
  client/components/post.vue
  client/layouts/default.vue
  client/nuxt.config.js
  client/pages/s/_station/post/_post/index.vue
  node_modules/.yarn-integrity
  server/api/postAPI.js
  server/middlewares/queryMw.js
  server/routers/postRtr.js
  server/test/integration/postAPI.spec.js
  server/test/unit/postAPI.test.js
  server/test/unit/queryMw.test.js
  yarn.lock
Labels: enhancement, ui

#51 Fix us20
  client/pages/sign-up.vue
  server/api/userAPI.js
  server/middlewares/loginMw.js
  server/middlewares/postMw.js
  server/middlewares/stationMw.js
  server/middlewares/userMw.js
  server/migrations/sqls/up.sql
  server/package.json
  server/test/integration/userAPI.spec.js
  server/test/unit/ajvErrors.test.js
  server/test/unit/userAPI.test.js
  server/yarn-error.log
  server/yarn.lock
Labels: fix

#52 Fix us23 24
  client/components/comment.vue
  client/components/post-preview.vue
  client/components/post.vue
  client/pages/s/_station/post/_post/index.vue
  server/middlewares/stationMw.js
Labels: fix

#54 Fix 33
  client/pages/s/_station/add-post.vue
  client/pages/s/_station/post/_post/index.vue
Labels: fix
